apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
spec:
  ingressClassName: nginx
  rules:
    - host: www.ab31cd44077b14e7aa074d45ec52949d-206787249.eu-north-1.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: main
                port:
                  number: 4000

    - host: web1.ab31cd44077b14e7aa074d45ec52949d-206787249.eu-north-1.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web1
                port:
                  number: 80

    - host: web2.ab31cd44077b14e7aa074d45ec52949d-206787249.eu-north-1.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web2
                port:
                  number: 8080
