apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deployment-autoscaling
  labels:
    app : my-k8s-app
    environment: production
    owner: Max
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cia
  template:
    metadata:
      labels:
        project: cia
    spec:
      containers:
      - name: cia-web
        image: fusrodah2077/k8s:latest
        ports:
        - containerPort: 4000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: myweb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myweb-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80